import argparse
import os
from datetime import datetime
from pathlib import Path
from typing import Final


# NOTE: In conformance with PEP517, versions should be stored as:
# `__version__ = 'a.b.c'` (e.g., no f-string)
# In order to dynamically set the version string, we use this script
# to write the version declaration to `version.py`.
VERSION: Final[str] = "1.0.11"
DISCLAIMER: Final[str] = (
    "# This file is auto-generated by `create_version_file.py`.\n# It is not intended for manual editing."
)
VERSION_PATH: Final[Path] = Path.cwd() / "dicom_utils" / "version.py"
ALPHA_INDICATOR: Final[str] = "a"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=f"Updates `{VERSION_PATH}`")
    parser.add_argument("--decrement", help="decrement the alpha number", default=False, action="store_true")
    return parser.parse_args()


def get_version_modifier(decrement: bool = False) -> str:
    # This function updates the alpha number: 1.0.0 -> 1.0.0a0 -> 1.0.0a1 ...
    if VERSION_PATH.is_file():
        exec_result = {}
        exec(open(VERSION_PATH).read(), exec_result)
        __version__ = exec_result["__version__"]

        version_without_modifier = __version__.split(ALPHA_INDICATOR)[0]
        if version_without_modifier == VERSION:
            current_alpha_number = int(__version__.split(ALPHA_INDICATOR)[-1]) if ALPHA_INDICATOR in __version__ else -1
            alpha_number = current_alpha_number + (-1 if decrement else 1)
            return f"{ALPHA_INDICATOR}{alpha_number}" if alpha_number > -1 else "-UNDEFINED"

    return ""


def main(args: argparse.Namespace):
    version_string = f"{VERSION}{get_version_modifier(args.decrement)}"
    if 1 == int(os.environ.get("CREATE_BUILD_NUMBER", 0)):
        # We use a YYYYMMDDHHMMSS timestamp in UTC as our build number since it is unique,
        # easy to generate, and has meaning.
        version_string += datetime.utcnow().strftime("%Y%m%d%H%M%S")
    with open(VERSION_PATH, "w") as f:
        f.write(f'{DISCLAIMER}\n__version__ = "{version_string}"\n')


if __name__ == "__main__":
    main(parse_args())
